---
version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - errcheck
    - goconst
    # - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    # - revive
    - staticcheck
    - unconvert
    # - unparam
    - unused

# Instead of disabling tests entirely, just ignore goconst, which is the only
# one with issues there currently.
issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - goconst
