---
service:
  golangci-lint-version: 1.63.x

linters:
  enable:
    - errcheck
    - goconst
    - gofmt
    - goimports
    # - gosec
    - gosimple
    - govet
    - ineffassign
    - megacheck
    - misspell
    - nakedret
    # - revive
    - staticcheck
    - typecheck
    - unconvert
    # - unparam
    - unused
    - vet
    - vetshadow

# Instead of disabling tests entirely, just ignore goconst, which is the only
# one with issues there currently.
issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - goconst
