project_name: circleci-cli

archive:
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip


builds:
  - binary: circleci
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      # -s Omit the symbol table and debug information.
      # -w Omit the DWARF symbol table.
      # These are the defaults specified by goreleaser:
      # https://github.com/goreleaser/goreleaser/blob/682c811106f56ffe06c4212de546aec62161fb9d/internal/builders/golang/build.go#L46
      - -s -w -X version.Version={{.Version}} -X version.Commit={{.Commit}}
