project_name: circleci-cli

git:
  short_hash: true

archive:
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip

snapcraft:
  name: circleci
  summary: "Run local CI builds and validate configuration."
  description: |
    The CircleCI Local CLI allows you to run builds on your local machine as if they were running within CircleCI. This allows quick interation over small changes and easier debugging of issues. The Local CLI can also validate your CircleCI configuration file.
  grade: stable
  confinement: strict
  apps:
    circleci:
      command: circleci
      plugs: [docker]

builds:
  - binary: circleci
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      # -s Omit the symbol table and debug information.
      # -w Omit the DWARF symbol table.
      # These are the defaults specified by goreleaser:
      # https://github.com/goreleaser/goreleaser/blob/682c811106f56ffe06c4212de546aec62161fb9d/internal/builders/golang/build.go#L46
      - -s -w -X github.com/CircleCI-Public/circleci-cli/version.Version={{.Version}} -X github.com/CircleCI-Public/circleci-cli/version.Commit={{.Commit}}
