project_name: circleci-cli

git:
  short_hash: true

archive:
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
  files:
    - client/LICENSE
    - md_docs/LICENSE

before:
  hooks:
  - make pack

builds:
  - binary: circleci
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      # -s Omit the symbol table and debug information.
      # -w Omit the DWARF symbol table.
      # These are the defaults specified by goreleaser:
      # https://github.com/goreleaser/goreleaser/blob/682c811106f56ffe06c4212de546aec62161fb9d/internal/builders/golang/build.go#L46
      - -s -w -X github.com/CircleCI-Public/circleci-cli/version.Version={{.Version}} -X github.com/CircleCI-Public/circleci-cli/version.Commit={{.Commit}} -X github.com/CircleCI-Public/circleci-cli/cmd.PackageManager=release
