version: '3.8'
services:
  dev: &dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    # HERE Most of the way there but now we're in trouble because we're
    # running Docker for Mac. I think we should just forget it and go with
    # a Vagrantfile that sets up docker.
    volumes:
      - ~/.circleci:/root/.circleci
      - /var/run/docker.sock:/var/run/docker.sock
  interactive:
    <<: *dev
    working_dir: /tmp/project
    entrypoint: ''
    command: bash
    volumes:
      - ~/.circleci:/root/.circleci
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/tmp/project
  test:
    <<: *dev
    command: ['test']
