FROM golang:1.12.17-buster@sha256:d9d06cb747d49db5d5703610ecdef837c0432efcaccc4a5959155dd61fe42f4a AS deps

RUN apt-get -qq update && \
      apt-get -qq install --no-install-recommends git && \
      rm -rf /var/lib/apt/lists/*

WORKDIR /project

COPY go.mod go.sum ./

RUN go mod download

RUN apt-get -qq update && \
      apt-get -qq install --no-install-recommends make bash && \
      rm -rf /var/lib/apt/lists/*

COPY . ./

RUN make

ENTRYPOINT ["make"]

FROM golang:1.12.17-buster@sha256:d9d06cb747d49db5d5703610ecdef837c0432efcaccc4a5959155dd61fe42f4a

RUN apt-get -qq update && \
      apt-get -qq install --no-install-recommends apt-transport-https \
                                                  ca-certificates \
                                                  curl \
                                                  gnupg-agent \
                                                  software-properties-common \
                                                  lxc \
                                                  iptables && \
      curl -fsSL https://download.docker.com/linux/debian/gpg | \
        APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=true apt-key add - && \
      add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" && \
      apt-get -qq update && \
      apt-get -qq install --no-install-recommends docker-ce && \
      add-apt-repository --remove "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" && \
      apt-get -qq purge apt-transport-https \
                        curl \
                        gnupg-agent \
                        software-properties-common && \
      rm -rf /var/lib/apt/list/*

VOLUME /var/lib/docker

COPY --from=deps /project/build/linux/amd64/circleci /usr/local/bin/circleci

COPY bin/dev-entrypoint /usr/local/bin/

RUN chmod +x /usr/local/bin/dev-entrypoint

ENV CIRCLECI_CLI_SKIP_UPDATE_CHECK true

ENTRYPOINT ["dev-entrypoint"]
