version: '3.8'
services:
  dev: &dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    # HERE docker-ce is installed on the image and daemon appears to start
    # but picard fails to be found.
    #
    # Downloading latest CircleCI build agent...
    # INFO[2020-10-07T13:27:18.978990600Z] Attempting next endpoint for pull after error: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: Error creating mount namespace before pivot: operation not permitted
    # Error: Could not find picard image: failed to pull latest docker image: exit status 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  interactive:
    <<: *dev
    volumes:
      - .:/project
  test:
    <<: *dev
    command: ['test']
