// Copyright (c) 2026 Circle Internet Services, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//
// SPDX-License-Identifier: MIT

package cmdconfig

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/MakeNowJust/heredoc"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	clierrors "github.com/CircleCI-Public/circleci-cli/internal/errors"
	"github.com/CircleCI-Public/circleci-cli/internal/iostream"
	"github.com/CircleCI-Public/circleci-cli/internal/reposcan"
)

const generatedHeader = "# Generated by circleci config generate\n"

// scan is the package-level seam for repository scanning. Tests swap it via
// SetScanForTest in export_test.go.
var scan = func(ctx context.Context, dir string) (*reposcan.Result, error) {
	return reposcan.NewDefaultScanner().Scan(ctx, dir)
}

func newGenerateCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "generate [path]",
		Short: "Generate .circleci/config.yml from a repository scan",
		Long: heredoc.Doc(`
			Detect the language stack, container image, and setup commands for a
			repository, then write a starter pipeline to <path>/.circleci/config.yml.

			If a config file already exists at that path, generate does not overwrite
			it; it prints a confirmation and exits successfully. The .circleci/
			directory is created if needed, and the file is written atomically.
		`),
		Example: heredoc.Doc(`
			# Generate a config for the current directory
			$ circleci config generate

			# Generate a config for a specific project path
			$ circleci config generate ./my-app

			# Re-run is a no-op when a config already exists
			$ circleci config generate
			✓ Using existing config at .circleci/config.yml
		`),
		Args: cobra.MaximumNArgs(1),
		RunE: runGenerate,
	}
	return cmd
}

func runGenerate(cmd *cobra.Command, args []string) error {
	ctx := iostream.FromCmd(cmd.Context(), cmd)

	dir := "."
	if len(args) == 1 {
		dir = args[0]
	}

	info, err := os.Stat(dir)
	if err != nil || !info.IsDir() {
		return clierrors.New(
			"config_generate.path_not_found",
			"Path not found",
			fmt.Sprintf("No directory exists at %q.", dir),
		).WithSuggestions(
			"Check the path you passed and try again",
			"Omit the argument to scan the current directory",
		).WithExitCode(clierrors.ExitBadArguments)
	}

	configPath := filepath.Join(dir, ".circleci", "config.yml")
	if _, err := os.Stat(configPath); err == nil {
		iostream.ErrPrintf(ctx, "%s Using existing config at %s\n",
			iostream.SymbolOK(ctx), configPath)
		return nil
	}

	result, err := scan(ctx, dir)
	if err != nil {
		return clierrors.New(
			"config_generate.scan_failed",
			"Repository scan failed",
			fmt.Sprintf("Could not detect the project stack: %s.", err),
		).WithSuggestions(
			"Re-run with --debug to see scan details",
			"Try again; image resolution requires network access",
		).WithExitCode(clierrors.ExitGeneralError)
	}

	reposcan.Render(ctx, result)

	body, err := renderConfig(result)
	if err != nil {
		return clierrors.New(
			"config_generate.render_failed",
			"Could not render config",
			fmt.Sprintf("YAML marshaling failed: %s.", err),
		).WithExitCode(clierrors.ExitGeneralError)
	}

	if err := writeConfigAtomic(configPath, body); err != nil {
		return clierrors.New(
			"config_generate.write_failed",
			"Could not write config",
			fmt.Sprintf("Failed to write %s: %s.", configPath, err),
		).WithExitCode(clierrors.ExitGeneralError)
	}

	iostream.ErrPrintf(ctx, "%s Generated %s\n", iostream.SymbolOK(ctx), configPath)
	return nil
}

// renderConfig builds the pipeline YAML body for a scan result. When the scan
// produced no usable detection (IsEmpty), a generic cimg/base:stable template
// is emitted with a placeholder build step. Output is deterministic: struct
// field order controls top-level layout and yaml.v3 sorts map keys
// alphabetically.
func renderConfig(r *reposcan.Result) ([]byte, error) {
	var image string
	steps := []step{{Checkout: true}}

	if r.IsEmpty() {
		image = "cimg/base:stable"
		steps = append(steps, step{Run: &runStep{
			Name:    "build",
			Command: `echo "Add your build steps here"`,
		}})
	} else {
		image = r.Image
		if r.ImageVersion != "" {
			image = r.Image + ":" + r.ImageVersion
		}
		for _, s := range r.Setup {
			steps = append(steps, step{Run: &runStep{Name: s.Name, Command: s.Command}})
		}
	}

	p := pipeline{
		Version: "2.1",
		Jobs: map[string]pipelineJob{
			"build": {
				Docker: []dockerImage{{Image: image}},
				Steps:  steps,
			},
		},
		Workflows: map[string]workflow{
			"build": {Jobs: []string{"build"}},
		},
	}

	var buf bytes.Buffer
	buf.WriteString(generatedHeader)

	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(p); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// writeConfigAtomic writes body to path via a temp file in the same directory
// followed by os.Rename. The .circleci directory is created if missing.
func writeConfigAtomic(path string, body []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	tmp, err := os.CreateTemp(filepath.Dir(path), "config.*.yml.tmp")
	if err != nil {
		return err
	}

	if _, err := tmp.Write(body); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmp.Name(), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}

type pipeline struct {
	Version   string                 `yaml:"version"`
	Jobs      map[string]pipelineJob `yaml:"jobs"`
	Workflows map[string]workflow    `yaml:"workflows"`
}

type pipelineJob struct {
	Docker []dockerImage `yaml:"docker"`
	Steps  []step        `yaml:"steps"`
}

type dockerImage struct {
	Image string `yaml:"image"`
}

type workflow struct {
	Jobs []string `yaml:"jobs"`
}

// step is either a bare "checkout" string or a "run" map. The custom
// MarshalYAML selects the right form so the rendered YAML matches the
// canonical CircleCI shape.
type step struct {
	Checkout bool
	Run      *runStep
}

type runStep struct {
	Name    string `yaml:"name"`
	Command string `yaml:"command"`
}

func (s step) MarshalYAML() (interface{}, error) {
	if s.Checkout {
		return "checkout", nil
	}
	return map[string]*runStep{"run": s.Run}, nil
}
