version: 2.1

parameters:
  go_version_with_patch:
    type: string
    default: 1.26.2

orbs:
  go: circleci/go@3.0.4

commands:
  setup:
    steps:
      - checkout
      - install-go
      - install-task
      - run: task mod-download


  install-go:
    # TODO: Fix the Go orb install command, so it supports Windows.
    steps:
      - run:
          name: Install Go
          command: |
            arch="$(uname -m)"
            case $arch in
              "x86_64")
                ARCH=amd64
                ;;
              "aarch64")
                ARCH=arm64
                ;;
              "arm64")
                ARCH=arm64
                ;;
              *)
                echo "Unknown architecture: $arch"
                exit 1
                ;;
            esac
            echo "Detected architecture: $ARCH"
            
            os="$(uname -o)"
            case "$os" in
              "Darwin")
                OS=darwin
                ;;
              "Msys")
                OS=windows
                ;;
              "GNU/Linux")
                OS=linux
                ;;
              *)
                echo "Unknown OS: $os"
                exit 1
                ;;
            esac
            echo "Detected OS: $OS"
            
            EXTENSION="tar.gz"
            if [[ "$OS" == "windows" ]]; then
              EXTENSION="zip"
            fi
            URL="https://golang.org/dl/go<< pipeline.parameters.go_version_with_patch >>.${OS}-${ARCH}.${EXTENSION}"
            echo "Downloading Go from $URL"
            
            if [[ "$OS" == "windows" ]]; then
              rm -rf /c/go
              curl -o /tmp/go.zip -fsSL "$URL" 
              unzip -q -d /c/ /tmp/go.zip
            else
              echo 'export PATH="/usr/local/go/bin:$HOME/go/bin:$PATH"' >> "$BASH_ENV"
              . "$BASH_ENV"
              rm -rf /usr/local/go
              curl -fsSL "$URL" | sudo tar -C /usr/local -xz
            fi
            
            go version

  install-task:
    steps:
      - run:
          name: Install go-task
          command: |
            sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b "$HOME/.local/bin"
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$BASH_ENV"

  store_results:
    steps:
      - store_test_results:
          path: ./test-reports

executors:
  linux:
    docker:
      - image: cimg/base:stable
    resource_class: large

  macos:
    macos:
      xcode: 26.5.0
    environment:
      # Work around Go orb not knowing where the cache is on MacOS (assuming ~/.cache/go-build).
      GOCACHE: '/Users/distiller/.cache/go-build'

  windows:
    machine: true
    resource_class: windows.medium
    environment:
      # Work around Go orb not knowing where the cache is on Windows (assuming ~/.cache/go-build).
      GOCACHE: 'C:\Users\circleci\.cache\go-build'

jobs:
  lint:
    executor: linux
    steps:
      - setup
      - go/with-cache:
          golangci-lint: true
          steps:
            - run: task ci:lint
            - store_results
            - run: task ci:diff

  test:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - setup
      - run: go env GOCACHE
      - go/with-cache:
          key: 'v1'
          steps:
            - run: task ci:test
            - store_results

workflows:
  ci:
    jobs:
      - lint
      - test:
          matrix:
            parameters:
              executor:
                - linux
                - macos
                - windows
