// Copyright (c) 2026 Circle Internet Services, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//
// SPDX-License-Identifier: MIT

package runnerconfig

const containerHeader = `# Helm values for container runner (container-agent chart),
# generated by circleci runner config.
#
# Install with: helm install container-agent container-agent/container-agent \
#   -n circleci -f <path to this file>
#
# Contains a runner token in plain text. Do not commit it. To keep the token out
# of Helm values, put it in a Kubernetes Secret and set agent.customSecret:
# https://circleci.com/docs/guides/execution-runner/container-runner/#custom-secret
`

const provisionerHeader = `# Helm values for runner provisioner (runner-provisioner chart),
# generated by circleci runner config.
#
# scaling, runner and the VM spec are inherited from the chart's
# resourceClassDefaults, so a token is all a resource class needs here.
#
# Contains a runner token in plain text. Do not commit it. To keep the token out
# of Helm values, put it in a Kubernetes Secret with a secrets.yaml key and set
# provisioner.existingSecret.
`

// resourceClass is one entry in either chart's resourceClasses map. Both charts
// accept far more per class, but everything else has a chart-side default.
type resourceClass struct {
	Token string `yaml:"token"`
}

type containerValues struct {
	Agent containerAgent `yaml:"agent"`
}

type containerAgent struct {
	ResourceClasses map[string]resourceClass `yaml:"resourceClasses"`
}

type provisionerValues struct {
	Provisioner provisionerSection `yaml:"provisioner"`
}

type provisionerSection struct {
	ResourceClasses map[string]resourceClass `yaml:"resourceClasses"`
}

func renderContainer(opts Options) ([]byte, error) {
	return encode(containerHeader, containerValues{
		Agent: containerAgent{
			ResourceClasses: map[string]resourceClass{
				opts.ResourceClass: {Token: opts.Token},
			},
		},
	})
}

func renderProvisioner(opts Options) ([]byte, error) {
	return encode(provisionerHeader, provisionerValues{
		Provisioner: provisionerSection{
			ResourceClasses: map[string]resourceClass{
				opts.ResourceClass: {Token: opts.Token},
			},
		},
	})
}
