// Copyright (c) 2026 Circle Internet Services, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//
// SPDX-License-Identifier: MIT

package runnerconfig

// DefaultWorkingDirectory matches the working directory in the packaged agent
// config that the deb and rpm install to /etc/circleci-runner, so a generated
// file behaves the same as a package install.
const DefaultWorkingDirectory = "/var/lib/circleci-runner/workdir"

const machineHeader = `# Machine runner 3 agent configuration (circleci-runner 3.x),
# generated by circleci runner config.
#
# Start the agent with: circleci-runner machine -c <path to this file>
# Contains a runner token in plain text. Do not commit it.
# Reference: https://circleci.com/docs/guides/execution-runner/machine-runner-3-configuration-reference/
`

// machineConfig is the subset of the agent's schema a working install needs.
// Every other field the agent accepts has a usable default, so emitting it here
// would only restate the default. Field order controls the emitted layout.
type machineConfig struct {
	API     machineAPI     `yaml:"api"`
	Runner  machineRunner  `yaml:"runner"`
	Logging machineLogging `yaml:"logging"`
}

type machineAPI struct {
	AuthToken string `yaml:"auth_token"`
}

type machineRunner struct {
	Name                    string `yaml:"name"`
	WorkingDirectory        string `yaml:"working_directory"`
	CleanupWorkingDirectory bool   `yaml:"cleanup_working_directory"`
}

type machineLogging struct {
	Level  string `yaml:"level"`
	Format string `yaml:"format"`
	File   string `yaml:"file"`
}

func renderMachine(opts Options) ([]byte, error) {
	if err := ValidateName(opts.Name); err != nil {
		return nil, err
	}

	workDir := opts.WorkingDirectory
	if workDir == "" {
		workDir = DefaultWorkingDirectory
	}

	return encode(machineHeader, machineConfig{
		API: machineAPI{AuthToken: opts.Token},
		Runner: machineRunner{
			Name:                    opts.Name,
			WorkingDirectory:        workDir,
			CleanupWorkingDirectory: true,
		},
		Logging: machineLogging{
			// "text" rather than the agent's "color" default: this config is
			// normally read by a systemd service logging to a file or journal,
			// where escape codes are noise.
			Level:  "info",
			Format: "text",
			File:   "-",
		},
	})
}
