// Copyright (c) 2026 Circle Internet Services, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//
// SPDX-License-Identifier: MIT

package acceptance_test

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"gotest.tools/v3/assert"
	"gotest.tools/v3/golden"

	"github.com/CircleCI-Public/circleci-cli/internal/testing/binary"
	testenv "github.com/CircleCI-Public/circleci-cli/internal/testing/env"
)

// normalizeStderr replaces dir with placeholder and flips any remaining
// Windows backslashes to forward slashes so .stderr.txt goldens are stable
// across platforms.
func normalizeStderr(stderr, dir, placeholder string) string {
	s := strings.ReplaceAll(stderr, dir, placeholder)
	return strings.ReplaceAll(s, `\`, `/`)
}

// TestConfigGenerate_SkipsWhenExists exercises the idempotent re-run path
// from a real binary.
func TestConfigGenerate_SkipsWhenExists(t *testing.T) {
	dir := t.TempDir()
	configDir := filepath.Join(dir, ".circleci")
	assert.NilError(t, os.MkdirAll(configDir, 0o755))
	configPath := filepath.Join(configDir, "config.yml")
	original := []byte("# user's existing config\nversion: 2.1\n")
	assert.NilError(t, os.WriteFile(configPath, original, 0o644))

	env := testenv.New(t)
	result := binary.RunCLI(t, binary.RunOpts{
		Binary:  binaryPath,
		Args:    []string{"config", "generate", dir},
		Env:     env.Environ(),
		WorkDir: t.TempDir(),
	})

	assert.Equal(t, result.ExitCode, 0, "stderr: %s", result.Stderr)
	assert.Equal(t, result.Stdout, "")

	stderr := normalizeStderr(result.Stderr, dir, "<DIR>")
	assert.Check(t, golden.String(stderr, t.Name()+".stderr.txt"))

	got, readErr := os.ReadFile(configPath)
	assert.NilError(t, readErr)
	assert.DeepEqual(t, got, original)
}

func TestConfigGenerate_PathNotFound(t *testing.T) {
	missing := filepath.Join(t.TempDir(), "does-not-exist")

	env := testenv.New(t)
	result := binary.RunCLI(t, binary.RunOpts{
		Binary:  binaryPath,
		Args:    []string{"config", "generate", missing},
		Env:     env.Environ(),
		WorkDir: t.TempDir(),
	})

	assert.Equal(t, result.ExitCode, 2, "expected ExitBadArguments, stderr: %s", result.Stderr)
	assert.Equal(t, result.Stdout, "")

	// The error message renders the path with %q, which escapes Windows
	// backslashes (e.g. C:\\Users\\…). Match the quoted form so the
	// substitution works on every platform.
	stderr := strings.ReplaceAll(result.Stderr, strconv.Quote(missing), `"<MISSING_PATH>"`)
	assert.Check(t, golden.String(stderr, t.Name()+".stderr.txt"))
}

// fixturePath returns the absolute path to a JSON scan fixture under
// acceptance/testdata/fixtures/.
func fixturePath(t *testing.T, name string) string {
	t.Helper()
	abs, err := filepath.Abs(filepath.Join("testdata", "fixtures", name))
	assert.NilError(t, err)
	return abs
}

// generatedHeader mirrors the constant in internal/configgen. It's duplicated
// here so the acceptance test asserts the wire contract without importing
// production internals.
const generatedHeader = "# Generated by circleci config generate\n"

// TestConfigGenerate_WritesGeneratedYAML exercises the success-write path
// end-to-end through the real binary: the testfixtures scan hook flows into
// configgen, which writes a non-empty file via the atomic temp+rename path
// and prints the "Generated <path>" summary to stderr. YAML shape is owned by
// internal/configgen tests; here we only assert the wiring produced something
// configgen could have written.
func TestConfigGenerate_WritesGeneratedYAML(t *testing.T) {
	dir := t.TempDir()

	env := testenv.New(t)
	env.Extra["CIRCLECI_SCAN_FIXTURE"] = fixturePath(t, "scan-node.json")
	result := binary.RunCLI(t, binary.RunOpts{
		Binary:  binaryPath,
		Args:    []string{"config", "generate", dir},
		Env:     env.Environ(),
		WorkDir: t.TempDir(),
	})

	assert.Equal(t, result.ExitCode, 0, "stderr: %s", result.Stderr)
	assert.Equal(t, result.Stdout, "")

	written, readErr := os.ReadFile(filepath.Join(dir, ".circleci", "config.yml"))
	assert.NilError(t, readErr)
	assert.Assert(t, len(written) > 0, "config.yml must not be empty")
	assert.Assert(t, strings.HasPrefix(string(written), generatedHeader),
		"config.yml must start with the generated-by header; got: %q", string(written))

	stderr := normalizeStderr(result.Stderr, dir, "<DIR>")
	assert.Check(t, golden.String(stderr, t.Name()+".stderr.txt"))
}

// TestConfigGenerate_DefaultPath exercises the most common invocation: running
// "config generate" with no path argument so the command uses the current
// working directory.
func TestConfigGenerate_DefaultPath(t *testing.T) {
	dir := t.TempDir()

	env := testenv.New(t)
	env.Extra["CIRCLECI_SCAN_FIXTURE"] = fixturePath(t, "scan-node.json")
	result := binary.RunCLI(t, binary.RunOpts{
		Binary:  binaryPath,
		Args:    []string{"config", "generate"},
		Env:     env.Environ(),
		WorkDir: dir,
	})

	assert.Equal(t, result.ExitCode, 0, "stderr: %s", result.Stderr)
	assert.Equal(t, result.Stdout, "")

	written, readErr := os.ReadFile(filepath.Join(dir, ".circleci", "config.yml"))
	assert.NilError(t, readErr)
	assert.Assert(t, len(written) > 0, "config.yml must not be empty")
	assert.Assert(t, strings.HasPrefix(string(written), generatedHeader),
		"config.yml must start with the generated-by header; got: %q", string(written))

	stderr := strings.ReplaceAll(result.Stderr, `\`, `/`)
	assert.Check(t, golden.String(stderr, t.Name()+".stderr.txt"))
}

// TestConfigGenerate_ScanFailure exercises the structured-error path for a
// scanner failure end-to-end. The fixture file's "error" field forces the
// stubbed scanner to return that message.
func TestConfigGenerate_ScanFailure(t *testing.T) {
	dir := t.TempDir()

	env := testenv.New(t)
	env.Extra["CIRCLECI_SCAN_FIXTURE"] = fixturePath(t, "scan-error.json")
	result := binary.RunCLI(t, binary.RunOpts{
		Binary:  binaryPath,
		Args:    []string{"config", "generate", dir},
		Env:     env.Environ(),
		WorkDir: t.TempDir(),
	})

	assert.Equal(t, result.ExitCode, 1, "expected ExitGeneralError, stderr: %s", result.Stderr)
	assert.Equal(t, result.Stdout, "")
	assert.Check(t, golden.String(result.Stderr, t.Name()+".stderr.txt"))

	_, err := os.Stat(filepath.Join(dir, ".circleci", "config.yml"))
	assert.Assert(t, os.IsNotExist(err), "config.yml must not be written when scan fails")
}
