// Copyright (c) 2026 Circle Internet Services, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//
// SPDX-License-Identifier: MIT

// Package pack merges a directory tree of YAML files into a single YAML document.
//
// The merge rules are consistent across all CircleCI YAML packing (config and orbs):
//
//   - Files at the pack root are merged at the top level of the output.
//   - Subdirectory names become top-level YAML keys; files inside become entries
//     under that key, keyed by filename without extension.
//   - Deeper subdirectories are organisational only: their files join the
//     top-level section their ancestor opened, so commands/aws/login.yml becomes
//     commands.login. Two files that would claim the same key are an error.
//   - Files whose names begin with "@" are merged at the current directory level
//     rather than nested under a key (used for base files like @orb.yml).
//   - Dotfiles and non-YAML files are skipped.
//   - Packing a single file round-trips it through the YAML parser (normalising
//     formatting) and returns the result.
//   - Unquoted yes/no/on/off are booleans, as the CircleCI config compiler reads
//     them, not strings as YAML 1.2 would.
//   - A YAML anchor defined in one file may be aliased from any other file in the
//     tree; the alias is replaced by the anchored value in the output.
//   - Output is indented with four spaces, matching the 0.1.x CLI byte for byte.
package pack

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

// indent is the number of spaces per YAML nesting level in packed output.
//
// Packed configs and orbs are commonly generated by a hook and committed, so the
// exact whitespace is part of the contract: changing it rewrites every line of
// every committed packed file. Four is what the 0.1.x CLI emitted — it marshalled
// with gopkg.in/yaml.v3's default indent — so packing with either CLI produces
// the same bytes and neither churns the other's output.
const indent = 4

// Warning is a problem found while packing that does not stop the pack. Packing
// is a mechanical merge, so anything it notices about the *meaning* of the input
// is advisory: the merge still produces output.
type Warning struct {
	// Path is the file the problem is in.
	Path string
	// Line is the 1-indexed line within Path.
	Line int
	// Message describes the problem and what to do about it.
	Message string
}

// String renders the warning with its location leading, in the file:line: form
// editors and terminals turn into a clickable link.
func (w Warning) String() string {
	return fmt.Sprintf("%s:%d: %s", w.Path, w.Line, w.Message)
}

// Option configures a Pack call.
type Option func(*options)

type options struct {
	resolveIncludes bool
}

// WithIncludes enables resolution of `<< include(file) >>` directives: a scalar
// whose entire value is such a directive is replaced with the contents of the
// referenced file, resolved relative to the pack root. This is an orb-authoring
// feature — config packing does not use it. See resolveIncludes.
func WithIncludes() Option {
	return func(o *options) { o.resolveIncludes = true }
}

// Pack reads all YAML files under rootPath and merges them into a single YAML
// document. If rootPath is a single file it is parsed and re-serialised.
//
// The returned warnings describe anything noticed about the input that is
// suspicious but not fatal. They are ordered by the lexical file walk, so they
// are stable across runs, and callers that have nowhere to show them may discard
// them.
func Pack(rootPath string, opts ...Option) (string, []Warning, error) {
	var o options
	for _, opt := range opts {
		opt(&o)
	}

	absRoot, err := filepath.Abs(rootPath)
	if err != nil {
		return "", nil, fmt.Errorf("resolving path: %w", err)
	}

	info, err := os.Stat(absRoot)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil, fmt.Errorf("accessing %q: no such file or directory", rootPath)
		}
		return "", nil, fmt.Errorf("accessing %q: %w", rootPath, err)
	}

	var (
		result   map[string]any
		warnings []Warning
	)
	if info.IsDir() {
		// Anchors are collected up front so a file may alias an anchor defined
		// in any other file of the tree, not just its own.
		result, err = packDir(absRoot, 0, collectAnchors(absRoot), &warnings)
	} else {
		// A single file has nothing else to draw anchors from.
		result, err = packFile(absRoot, nil, &warnings)
	}
	if err != nil {
		return "", nil, err
	}

	if o.resolveIncludes {
		// Includes resolve relative to the pack root directory, or the
		// containing directory when a single file is packed.
		baseDir := absRoot
		if !info.IsDir() {
			baseDir = filepath.Dir(absRoot)
		}
		if err := resolveIncludes(result, baseDir); err != nil {
			return "", nil, err
		}
	}

	var buf strings.Builder
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(indent)
	err = enc.Encode(result)
	if err != nil {
		return "", nil, fmt.Errorf("marshaling result: %w", err)
	}
	return buf.String(), warnings, nil
}

// packDir recursively merges all YAML files under dirPath.
//
// depth is the nesting level below the pack root, and it decides what a
// subdirectory means:
//
//   - At depth 0 (the pack root) a subdirectory opens a top-level section:
//     src/commands/ becomes the "commands" key.
//   - Below that, subdirectories are organisational only. Their files join the
//     section their ancestor opened, keyed by filename, so
//     src/commands/aws/login.yml becomes commands.login rather than
//     commands.aws.login — which was not a command at all, just a map that
//     happened to sit where one belonged.
//
// anchors holds the anchors defined anywhere in the tree; see collectAnchors.
// warnings accumulates advisory findings; see Warning.
func packDir(dirPath string, depth int, anchors map[string]*yaml.Node, warnings *[]Warning) (map[string]any, error) {
	entries, err := os.ReadDir(dirPath)
	if err != nil {
		return nil, fmt.Errorf("reading directory %q: %w", dirPath, err)
	}

	subtree := make(map[string]any)
	dirBasename := nameWithoutExt(filepath.Base(dirPath))

	// origins records which file or directory claimed each key at this level, so
	// a collision between two sources can name both of them. Only populated
	// below the root, where flattening makes collisions possible.
	origins := make(map[string]string)

	// Subdirectory results are held back and merged after the files at this
	// level, so a collision is caught whichever order os.ReadDir returns them
	// in: commands/login.yml and commands/aws/login.yml collide either way.
	type nestedResult struct {
		path    string
		content map[string]any
	}
	var nested []nestedResult

	for _, entry := range entries {
		name := entry.Name()
		fullPath := filepath.Join(dirPath, name)

		if strings.HasPrefix(name, ".") {
			continue
		}

		if entry.IsDir() {
			childMap, err := packDir(fullPath, depth+1, anchors, warnings)
			if err != nil {
				return nil, err
			}
			if depth == 0 {
				existing, _ := subtree[name].(map[string]any)
				merged := mergeMaps(existing, childMap)
				// A root subdirectory with no YAML content is not a section: it
				// holds sidecar files such as the scripts an orb pulls in with
				// << include(...) >>. Emitting it as an empty "scripts: {}" key
				// would invent a top-level section the author never wrote.
				if len(merged) > 0 {
					subtree[name] = merged
				}
			} else {
				nested = append(nested, nestedResult{path: fullPath, content: childMap})
			}
			continue
		}

		if !isYAMLName(name) {
			continue
		}

		content, err := packFile(fullPath, anchors, warnings)
		if err != nil {
			return nil, err
		}

		switch {
		case depth == 0:
			// Files directly under the pack root are merged at the top level.
			subtree = mergeMaps(subtree, content)
		case isSpecialName(name):
			// @*.yml files are merged at the current directory level rather than
			// nested under a key. The parent-dir key is consulted to pull in any
			// content already accumulated there (matching the original filetree behaviour).
			existing, _ := subtree[dirBasename].(map[string]any)
			subtree = mergeMaps(subtree, existing, content)
		default:
			key := nameWithoutExt(name)
			existing, _ := subtree[key].(map[string]any)
			subtree[key] = mergeMaps(existing, content)
			origins[key] = fullPath
		}
	}

	for _, n := range nested {
		for key := range n.content {
			if from, taken := origins[key]; taken {
				return nil, fmt.Errorf(
					"%q and %q both define %q; two files that pack into the same section cannot share a name",
					from, filepath.Join(n.path, key+".yml"), key)
			}
			origins[key] = filepath.Join(n.path, key+".yml")
		}
		subtree = mergeMaps(subtree, n.content)
	}

	return subtree, nil
}

// packFile reads and parses a single YAML file, returning its root map.
//
// anchors supplies the anchors defined elsewhere in the tree. A file that aliases
// one of them fails to parse on its own — anchors are a property of a single YAML
// document — so on that specific failure the parse is retried with those
// definitions prepended. Pass nil to parse the file in isolation.
//
// warnings accumulates advisory findings about this file; see Warning.
func packFile(path string, anchors map[string]*yaml.Node, warnings *[]Warning) (map[string]any, error) {
	b, err := os.ReadFile(path) //#nosec:G304 // path is a resolved filesystem path under the user-supplied pack root directory
	if err != nil {
		return nil, fmt.Errorf("reading %q: %w", path, err)
	}

	res, err := decodeYAML(b)
	if err != nil {
		res, err = retryWithAnchors(b, anchors, err)
		if err != nil {
			return nil, parseError(path, err)
		}
	}
	if res.node != nil {
		findDetachedListKeys(path, res.node, res.lineOffset, warnings)
	}

	v := res.value
	if v == nil {
		return make(map[string]any), nil
	}
	m := toStringMap(v)
	if m == nil {
		return nil, fmt.Errorf("%q must have a YAML map at the root, got %T", path, v)
	}
	return m, nil
}

// decodeYAML parses one YAML document into a Go value.
//
// It goes through a yaml.Node rather than straight into `any` so that plain
// YAML 1.1 booleans can be retagged before the value is materialised — see
// resolveYAML11Bools for why that matters. A file that is empty, or holds only
// comments, yields a nil value and no error.
//
// The separate Decode step is also what surfaces duplicate mapping keys:
// yaml.Unmarshal into a yaml.Node accepts them, and only the decode into a Go
// value reports them.
func decodeYAML(b []byte) (parsed, error) {
	var node yaml.Node
	if err := yaml.Unmarshal(b, &node); err != nil {
		return parsed{}, err
	}
	if node.Kind == 0 {
		return parsed{}, nil
	}

	resolveYAML11Bools(&node, false)

	var v any
	if err := node.Decode(&v); err != nil {
		return parsed{}, err
	}
	return parsed{value: v, node: &node}, nil
}

// parsed is a decoded document together with the node tree it came from, so a
// caller can still ask where in the source something was after the value has
// been materialised.
type parsed struct {
	value any
	node  *yaml.Node

	// lineOffset is how many lines were prepended ahead of the file's own first
	// line before parsing. Non-zero only on the cross-file anchor retry, which
	// parses a synthesised document; source positions must have it subtracted
	// before they are reported to the user.
	lineOffset int
}

// yaml11Bools maps the plain scalars that YAML 1.1 resolves as booleans, but
// YAML 1.2 — and therefore gopkg.in/yaml.v3 — resolves as strings.
//
// The single-character forms y/Y/n/N are deliberately absent. YAML 1.1 lists
// them, but SnakeYAML (which backs the CircleCI config compiler) does not
// resolve them as booleans, and "n" is a plausible string value in a real
// config. Matching the compiler matters more here than matching the spec.
var yaml11Bools = map[string]string{
	"yes": "true", "Yes": "true", "YES": "true",
	"on": "true", "On": "true", "ON": "true",
	"no": "false", "No": "false", "NO": "false",
	"off": "false", "Off": "false", "OFF": "false",
}

// resolveYAML11Bools retags unquoted yes/no/on/off scalars as booleans.
//
// The CircleCI config compiler reads YAML 1.1, where those six words are
// booleans. gopkg.in/yaml.v3 reads YAML 1.2, where they are strings — so
// packing decoded `default: on` to the string "on" and, because that string
// would be ambiguous on the way out, re-emitted it quoted. A boolean parameter
// then failed validation against its own declared type:
//
//	Parameter error: default value of parameter 'killswitch' is 'on' (type string): expected type boolean
//
// Retagging makes the packed output say what the compiler would have read from
// the source, which is the whole job of pack. `on` becomes `true` rather than
// an unquoted `on`: both are booleans in YAML 1.1 and 1.2, and `true` cannot be
// misread by either.
//
// Two things are left alone:
//
//   - Quoted scalars. A source that says "on" or 'on' asked for the string, and
//     yaml.v3 records that in Style, so the intent survives.
//   - Mapping keys. isKey tracks them through the walk. A key retagged to a
//     boolean would no longer decode into map[string]any, and CircleCI config
//     has no boolean keys.
func resolveYAML11Bools(n *yaml.Node, isKey bool) {
	if n == nil {
		return
	}
	if n.Kind == yaml.ScalarNode {
		if !isKey && n.Tag == "!!str" && n.Style == 0 {
			if b, ok := yaml11Bools[n.Value]; ok {
				n.Tag = "!!bool"
				n.Value = b
			}
		}
		return
	}
	// Mappings alternate key, value, key, value through Content.
	if n.Kind == yaml.MappingNode {
		for i, child := range n.Content {
			resolveYAML11Bools(child, i%2 == 0)
		}
		return
	}
	for _, child := range n.Content {
		resolveYAML11Bools(child, false)
	}
}

// anchorsKey is the throwaway top-level key the anchor definitions are hung
// from when a file is re-parsed. It is deleted before the file's content is
// merged. The name is not valid anywhere in a CircleCI config or orb, so it
// cannot shadow something real.
const anchorsKey = "__circleci_pack_anchors__"

// collectAnchors records every anchor defined by every YAML file under root.
//
// A decomposed orb naturally wants to define shared values once — conventionally
// in an anchors/@anchors.yml — and alias them from the files that need them. YAML
// will not do that on its own: an anchor is scoped to the document that defines
// it, so each file parsed alone fails with "unknown anchor".
//
// Files that fail to parse are skipped rather than reported. A file with an
// unresolved alias is exactly the case this exists to fix, and any genuine syntax
// error in it surfaces from the main pack pass with its own message.
//
// filepath.WalkDir visits lexically, so when two files define the same anchor
// name the later path wins, deterministically.
func collectAnchors(root string) map[string]*yaml.Node {
	anchors := make(map[string]*yaml.Node)

	// Reads go through an os.Root so they cannot follow a symlink out of the
	// pack directory between the walk seeing an entry and this opening it.
	dirRoot, err := os.OpenRoot(root)
	if err != nil {
		return anchors
	}
	// Close errors are immaterial here: this whole function is best-effort, and
	// every real problem with a file is reported by the main pack pass.
	defer func() { _ = dirRoot.Close() }()

	_ = filepath.WalkDir(root, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return nil //nolint:nilerr // unreadable entries are reported by the main pass
		}
		if strings.HasPrefix(d.Name(), ".") && path != root {
			if d.IsDir() {
				return fs.SkipDir
			}
			return nil
		}
		if d.IsDir() || !isYAMLName(d.Name()) {
			return nil
		}

		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return nil
		}
		b, readErr := dirRoot.ReadFile(rel)
		if readErr != nil {
			return nil
		}
		var node yaml.Node
		if yaml.Unmarshal(b, &node) != nil {
			return nil
		}
		collectNodeAnchors(&node, anchors)
		return nil
	})

	return anchors
}

// collectNodeAnchors walks a parsed document recording anchor definitions.
//
// An anchor whose own subtree contains an alias is skipped: re-serialising it in
// isolation would emit that alias with nothing to resolve it against, and one
// such anchor would break the definitions block for every file. Chaining an
// anchor to another anchor therefore only works within a single file.
func collectNodeAnchors(n *yaml.Node, into map[string]*yaml.Node) {
	if n == nil {
		return
	}
	if n.Anchor != "" && !containsAlias(n) {
		into[n.Anchor] = n
	}
	for _, child := range n.Content {
		collectNodeAnchors(child, into)
	}
}

func containsAlias(n *yaml.Node) bool {
	if n.Kind == yaml.AliasNode {
		return true
	}
	for _, child := range n.Content {
		if containsAlias(child) {
			return true
		}
	}
	return false
}

// retryWithAnchors re-parses src with anchors defined ahead of it, for a file
// whose only problem is an alias to an anchor defined in a sibling file.
//
// firstErr is the failure from parsing src alone. Anything other than an unknown
// anchor is returned untouched — this is not a general-purpose second chance.
//
// Which error to report when the retry also fails needs care, because the retry
// parses a synthesised document rather than the user's file:
//
//   - A *yaml.TypeError means the document parsed and only the decode into a Go
//     value objected — so the anchors did resolve, and the remaining problem
//     (a duplicate key, say) is real. Report it, with its line numbers shifted
//     back onto the user's file. Reporting firstErr here would claim the anchor
//     was unknown when it was not.
//   - Anything else is a parse failure that src alone did not have, so it is an
//     artifact of prepending the definitions — a file whose root is a sequence,
//     or one that opens its own document with ---. Report firstErr, which is at
//     least a true statement about the real file.
//
// The retry parses through decodeYAML rather than yaml.Unmarshal so that a file
// which needed a sibling's anchor is treated identically to every other file.
func retryWithAnchors(src []byte, anchors map[string]*yaml.Node, firstErr error) (parsed, error) {
	if len(anchors) == 0 || !isUnknownAnchorErr(firstErr) {
		return parsed{}, firstErr
	}

	prefix, err := anchorDefinitions(anchors)
	if err != nil {
		return parsed{}, firstErr
	}

	// decodeYAML, not a bare Unmarshal: a file that needed a sibling's anchor
	// must still get YAML 1.1 boolean retagging and duplicate-key detection.
	res, err := decodeYAML(append(prefix, src...))
	if err != nil {
		var typeErr *yaml.TypeError
		if errors.As(err, &typeErr) {
			return parsed{}, shiftLines(typeErr, bytes.Count(prefix, []byte("\n")))
		}
		return parsed{}, firstErr
	}
	// The definitions block did its job during parsing; the aliases in the file
	// are resolved values now, so drop it before the content is merged.
	if m, ok := res.value.(map[string]any); ok {
		delete(m, anchorsKey)
	}
	res.lineOffset = bytes.Count(prefix, []byte("\n"))
	return res, nil
}

// lineRefRe matches every line reference in a yaml.v3 decode message. A single
// message can carry more than one, as duplicate-key reports do:
// `line 3: mapping key "dupe" already defined at line 2`.
var lineRefRe = regexp.MustCompile(`line (\d+)`)

// shiftLines moves every line number in a decode error back by offset, undoing
// the lines that anchorDefinitions prepended, so the reported positions point at
// the file the user actually wrote.
func shiftLines(typeErr *yaml.TypeError, offset int) error {
	if offset == 0 {
		return typeErr
	}
	shifted := make([]string, 0, len(typeErr.Errors))
	for _, e := range typeErr.Errors {
		shifted = append(shifted, lineRefRe.ReplaceAllStringFunc(e, func(match string) string {
			n, convErr := strconv.Atoi(lineRefRe.FindStringSubmatch(match)[1])
			if convErr != nil || n-offset < 1 {
				return match
			}
			return fmt.Sprintf("line %d", n-offset)
		}))
	}
	return &yaml.TypeError{Errors: shifted}
}

// anchorDefinitions renders the collected anchors as a single-line mapping entry
// that can be prepended to a file, e.g.
//
//	__circleci_pack_anchors__: [&my-anchor my-value, &other {a: 1}]
//
// Flow style keeps it to one line and self-contained, so prepending it cannot
// disturb the indentation of what follows.
func anchorDefinitions(anchors map[string]*yaml.Node) ([]byte, error) {
	names := make([]string, 0, len(anchors))
	for name := range anchors {
		names = append(names, name)
	}
	sort.Strings(names)

	seq := &yaml.Node{Kind: yaml.SequenceNode, Style: yaml.FlowStyle}
	for _, name := range names {
		def := flowCopy(anchors[name])
		seq.Content = append(seq.Content, def)
	}

	doc := &yaml.Node{Kind: yaml.MappingNode, Content: []*yaml.Node{
		{Kind: yaml.ScalarNode, Tag: "!!str", Value: anchorsKey},
		seq,
	}}

	out, err := yaml.Marshal(doc)
	if err != nil {
		return nil, err
	}
	if !strings.HasSuffix(string(out), "\n") {
		out = append(out, '\n')
	}
	return out, nil
}

// flowCopy deep-copies a node with every collection forced to flow style, so it
// serialises on one line. Copying matters because the source nodes are shared
// across every file that needs them.
func flowCopy(n *yaml.Node) *yaml.Node {
	if n == nil {
		return nil
	}
	cp := *n
	cp.HeadComment, cp.LineComment, cp.FootComment = "", "", ""
	if cp.Kind == yaml.MappingNode || cp.Kind == yaml.SequenceNode {
		cp.Style = yaml.FlowStyle
	}
	cp.Content = nil
	for _, child := range n.Content {
		cp.Content = append(cp.Content, flowCopy(child))
	}
	return &cp
}

// isUnknownAnchorErr reports whether err is yaml.v3's undefined-alias failure.
// yaml.v3 gives it no distinct type, so the message is all there is to match on.
func isUnknownAnchorErr(err error) bool {
	return err != nil && strings.Contains(err.Error(), "unknown anchor")
}

// attachedKeys are keys that only mean anything as part of the thing above them:
// a workflow job's requires/context/filters, a step's name/command. Finding one
// as a *sibling* of a valueless key inside a list item is the signature of the
// mis-indentation this warning is about.
//
// Membership is deliberately narrow. The check only fires when one of these sits
// beside a valueless key in a sequence item, and a wrong warning is worse than a
// missing one.
var attachedKeys = map[string]bool{
	"requires":     true,
	"context":      true,
	"filters":      true,
	"matrix":       true,
	"name":         true,
	"type":         true,
	"pre-steps":    true,
	"post-steps":   true,
	"serial-group": true,
	"parameters":   true,
	"command":      true,
}

// findDetachedListKeys warns about a list item shaped like this:
//
//	jobs:
//	  - specs
//	  - other:
//	    requires:
//	      - specs
//
// `requires` is indented level with `other`, so YAML reads it as a *sibling* key
// of `other` in the same list item, and `other` itself has no value. Packing is a
// faithful merge, so it round-trips that as `other: null` alongside `requires`,
// which CircleCI then rejects at compile time:
//
//   - other: null
//     requires:
//   - specs
//
// The YAML is not malformed and pack is not wrong, so this is a warning rather
// than an error. But pack can see what was almost certainly meant, and saying so
// at pack time beats a compile error later with no file or line attached.
//
// The check is on shape alone, not on position in the document. A decomposed
// config puts `jobs:` at the top level of workflows/build_and_test.yml, so there
// is no workflows.*.jobs path to match on — and the same mis-indentation in a
// steps list deserves the same warning anyway.
func findDetachedListKeys(path string, n *yaml.Node, lineOffset int, warnings *[]Warning) {
	if n == nil {
		return
	}

	if n.Kind == yaml.SequenceNode {
		for _, item := range n.Content {
			if item.Kind == yaml.MappingNode {
				if w, ok := detachedKeyWarning(path, item, lineOffset); ok {
					*warnings = append(*warnings, w)
				}
			}
		}
	}

	for _, child := range n.Content {
		findDetachedListKeys(path, child, lineOffset, warnings)
	}
}

// detachedKeyWarning inspects one list item, reporting the valueless key and the
// attached key that looks like it was meant to belong to it.
//
// Both halves are required, and they must be different keys. A valueless key on
// its own is fine — `- specs:` is just a job with no configuration. An empty
// attached key on its own is fine too: `- image: alpine` with a bare `command:`
// under it is odd but says what it means.
func detachedKeyWarning(path string, item *yaml.Node, lineOffset int) (Warning, bool) {
	var (
		orphan   *yaml.Node // valueless key, i.e. the intended job or step name
		attached string     // the key that looks like it belongs to orphan
	)

	for i := 0; i+1 < len(item.Content); i += 2 {
		key, value := item.Content[i], item.Content[i+1]
		isAttached := attachedKeys[key.Value]
		isEmpty := value.Tag == "!!null"

		switch {
		case isEmpty && !isAttached && orphan == nil:
			orphan = key
		case !isEmpty && isAttached && attached == "":
			attached = key.Value
		}
	}

	if orphan == nil || attached == "" {
		return Warning{}, false
	}

	return Warning{
		Path: path,
		Line: orphan.Line - lineOffset,
		Message: fmt.Sprintf(
			"%q has no value but shares a list item with %q; indent %q one level further to attach it to %q",
			orphan.Value, attached, attached, orphan.Value),
	}, true
}

// mergeMaps shallow-merges any number of maps into a new map[string]any.
// nil inputs are silently skipped.
func mergeMaps(maps ...any) map[string]any {
	result := make(map[string]any)
	for _, m := range maps {
		if m == nil {
			continue
		}
		for k, v := range toStringMap(m) {
			result[k] = v
		}
	}
	return result
}

// toStringMap converts map[string]any or map[any]any (yaml.v2 legacy) to map[string]any.
func toStringMap(v any) map[string]any {
	switch m := v.(type) {
	case map[string]any:
		return m
	case map[any]any:
		out := make(map[string]any, len(m))
		for k, val := range m {
			if ks, ok := k.(string); ok {
				out[ks] = val
			}
		}
		return out
	}
	return nil
}

// yamlLineRe matches the "line N: " prefix that gopkg.in/yaml.v3 puts on the
// front of its messages. It appears on both top-level parse errors
// ("yaml: line 4: could not find expected ':'") and on each entry of a
// *yaml.TypeError ("line 6: mapping key \"auth\" already defined at line 3"),
// so one expression handles both after the "yaml: " prefix is trimmed.
var yamlLineRe = regexp.MustCompile(`^line (\d+): `)

// parseError rewrites a gopkg.in/yaml.v3 parse or decode failure so the source
// location leads the message, in the `file:line:` form that editors and
// terminals turn into a clickable link:
//
//	/path/to/src/executors/executorA.yml:6: mapping key "auth" already defined at line 3
//
// rather than yaml.v3's own shape, which buries the filename in prose and puts
// the line on a continuation line:
//
//	parsing "/path/to/src/executors/executorA.yml": yaml: unmarshal errors:
//	  line 6: mapping key "auth" already defined at line 3
//
// A *yaml.TypeError carries one entry per problem found; each gets its own
// located line so a file with several errors reports all of them. Messages with
// no line number degrade to "file: message" — still a location, just a coarser
// one. Columns are not available: yaml.v3 reports lines only.
func parseError(path string, err error) error {
	var typeErr *yaml.TypeError
	if errors.As(err, &typeErr) && len(typeErr.Errors) > 0 {
		located := make([]string, 0, len(typeErr.Errors))
		for _, e := range typeErr.Errors {
			located = append(located, locate(path, e))
		}
		return errors.New(strings.Join(located, "\n"))
	}
	return errors.New(locate(path, strings.TrimPrefix(err.Error(), "yaml: ")))
}

// locate prefixes msg with path, moving any leading "line N: " into the prefix
// so the result reads "path:N: msg".
func locate(path, msg string) string {
	if m := yamlLineRe.FindStringSubmatch(msg); m != nil {
		return fmt.Sprintf("%s:%s: %s", path, m[1], msg[len(m[0]):])
	}
	return fmt.Sprintf("%s: %s", path, msg)
}

var (
	yamlRe    = regexp.MustCompile(`.+\.(yml|yaml)$`)
	specialRe = regexp.MustCompile(`^@.+\.(yml|yaml)$`)
)

func isYAMLName(name string) bool    { return yamlRe.MatchString(name) }
func isSpecialName(name string) bool { return specialRe.MatchString(name) }

func nameWithoutExt(name string) string {
	return strings.TrimSuffix(name, filepath.Ext(name))
}

// includeRe matches a `<< include(path) >>` directive. Whitespace inside the
// guillemets is optional and the closing paren is tolerated as absent, matching
// the directive the 0.1.x CLI accepted byte for byte.
var includeRe = regexp.MustCompile(`<<[\s]*include\(([-\w/.]+)\)?[\s]*>>`)

// resolveIncludes replaces `<< include(file) >>` directives in the jobs,
// commands and executors sections of a packed orb with the contents of the
// referenced files.
//
// Only those three sections are searched, matching the 0.1.x CLI: includes are
// a way to pull a script or template into a step, so resolving them in, say, a
// description or an example would inline a file where the author meant to show
// the directive itself.
func resolveIncludes(result map[string]any, baseDir string) error {
	for _, key := range []string{"jobs", "commands", "executors"} {
		section, ok := result[key]
		if !ok {
			continue
		}
		resolved, err := resolveIncludeValue(section, baseDir)
		if err != nil {
			return err
		}
		result[key] = resolved
	}
	return nil
}

// resolveIncludeValue walks a decoded YAML value, replacing every scalar string
// that is a `<< include(file) >>` directive with the referenced file's contents.
// Maps and sequences are recursed into; other scalars are returned unchanged.
func resolveIncludeValue(v any, baseDir string) (any, error) {
	switch t := v.(type) {
	case string:
		return maybeIncludeFile(t, baseDir)
	case map[string]any:
		for k, val := range t {
			r, err := resolveIncludeValue(val, baseDir)
			if err != nil {
				return nil, err
			}
			t[k] = r
		}
		return t, nil
	case map[any]any:
		for k, val := range t {
			r, err := resolveIncludeValue(val, baseDir)
			if err != nil {
				return nil, err
			}
			t[k] = r
		}
		return t, nil
	case []any:
		for i, val := range t {
			r, err := resolveIncludeValue(val, baseDir)
			if err != nil {
				return nil, err
			}
			t[i] = r
		}
		return t, nil
	default:
		return v, nil
	}
}

// maybeIncludeFile returns the contents of the file named by a lone
// `<< include(file) >>` directive, or s unchanged when it holds no directive.
//
// The directive must be the entire value: a scalar is either an include or it
// is not, so a directive with text around it, or more than one directive in the
// same scalar, is an error rather than a partial substitution. `<<` sequences in
// the included file are escaped to `\<<` so the inlined content is never itself
// interpreted as parameter interpolation.
func maybeIncludeFile(s, baseDir string) (string, error) {
	// Find at most two matches: one is a valid include, more than one is the
	// error case, and there is no reason to scan further.
	matches := includeRe.FindAllStringSubmatch(s, 2)
	if len(matches) > 1 {
		return "", fmt.Errorf("multiple include statements in one value: %q", s)
	}
	if len(matches) == 0 {
		return s, nil
	}

	full, rel := matches[0][0], matches[0][1]
	if full != s {
		return "", fmt.Errorf("an include statement must be the entire value: %q", s)
	}

	path := filepath.Join(baseDir, rel)
	content, err := os.ReadFile(path) //#nosec:G304 // path is under the user-supplied pack root; includes are an author-controlled, local-only feature
	if err != nil {
		return "", fmt.Errorf("could not read included file %q: %w", path, err)
	}
	return strings.ReplaceAll(string(content), "<<", `\<<`), nil
}
