// Copyright (c) 2026 Circle Internet Services, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//
// SPDX-License-Identifier: MIT

// Package pack merges a directory tree of YAML files into a single YAML document.
//
// The merge rules are consistent across all CircleCI YAML packing (config and orbs):
//
//   - Files at the pack root are merged at the top level of the output.
//   - Subdirectory names become top-level YAML keys; files inside become entries
//     under that key, keyed by filename without extension.
//   - Deeper subdirectories are organisational only: their files join the
//     top-level section their ancestor opened, so commands/aws/login.yml becomes
//     commands.login. Two files that would claim the same key are an error.
//   - Files whose names begin with "@" are merged at the current directory level
//     rather than nested under a key (used for base files like @orb.yml).
//   - Dotfiles and non-YAML files are skipped.
//   - Packing a single file round-trips it through the YAML parser (normalising
//     formatting) and returns the result.
//   - Unquoted yes/no/on/off are booleans, as the CircleCI config compiler reads
//     them, not strings as YAML 1.2 would.
//   - A YAML anchor defined in one file may be aliased from any other file in the
//     tree; the alias is replaced by the anchored value in the output.
//   - Output is indented with four spaces, matching the 0.1.x CLI byte for byte.
package pack

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

// indent is the number of spaces per YAML nesting level in packed output.
//
// Packed configs and orbs are commonly generated by a hook and committed, so the
// exact whitespace is part of the contract: changing it rewrites every line of
// every committed packed file. Four is what the 0.1.x CLI emitted — it marshalled
// with gopkg.in/yaml.v3's default indent — so packing with either CLI produces
// the same bytes and neither churns the other's output.
const indent = 4

// Pack reads all YAML files under rootPath and merges them into a single YAML
// document. If rootPath is a single file it is parsed and re-serialised.
func Pack(rootPath string) (string, error) {
	absRoot, err := filepath.Abs(rootPath)
	if err != nil {
		return "", fmt.Errorf("resolving path: %w", err)
	}

	info, err := os.Stat(absRoot)
	if err != nil {
		if os.IsNotExist(err) {
			return "", fmt.Errorf("accessing %q: no such file or directory", rootPath)
		}
		return "", fmt.Errorf("accessing %q: %w", rootPath, err)
	}

	var result map[string]any
	if info.IsDir() {
		// Anchors are collected up front so a file may alias an anchor defined
		// in any other file of the tree, not just its own.
		result, err = packDir(absRoot, 0, collectAnchors(absRoot))
	} else {
		// A single file has nothing else to draw anchors from.
		result, err = packFile(absRoot, nil)
	}
	if err != nil {
		return "", err
	}

	var buf strings.Builder
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(indent)
	err = enc.Encode(result)
	if err != nil {
		return "", fmt.Errorf("marshaling result: %w", err)
	}
	return buf.String(), nil
}

// packDir recursively merges all YAML files under dirPath.
//
// depth is the nesting level below the pack root, and it decides what a
// subdirectory means:
//
//   - At depth 0 (the pack root) a subdirectory opens a top-level section:
//     src/commands/ becomes the "commands" key.
//   - Below that, subdirectories are organisational only. Their files join the
//     section their ancestor opened, keyed by filename, so
//     src/commands/aws/login.yml becomes commands.login rather than
//     commands.aws.login — which was not a command at all, just a map that
//     happened to sit where one belonged.
//
// anchors holds the anchors defined anywhere in the tree; see collectAnchors.
func packDir(dirPath string, depth int, anchors map[string]*yaml.Node) (map[string]any, error) {
	entries, err := os.ReadDir(dirPath)
	if err != nil {
		return nil, fmt.Errorf("reading directory %q: %w", dirPath, err)
	}

	subtree := make(map[string]any)
	dirBasename := nameWithoutExt(filepath.Base(dirPath))

	// origins records which file or directory claimed each key at this level, so
	// a collision between two sources can name both of them. Only populated
	// below the root, where flattening makes collisions possible.
	origins := make(map[string]string)

	// Subdirectory results are held back and merged after the files at this
	// level, so a collision is caught whichever order os.ReadDir returns them
	// in: commands/login.yml and commands/aws/login.yml collide either way.
	type nestedResult struct {
		path    string
		content map[string]any
	}
	var nested []nestedResult

	for _, entry := range entries {
		name := entry.Name()
		fullPath := filepath.Join(dirPath, name)

		if strings.HasPrefix(name, ".") {
			continue
		}

		if entry.IsDir() {
			childMap, err := packDir(fullPath, depth+1, anchors)
			if err != nil {
				return nil, err
			}
			if depth == 0 {
				existing, _ := subtree[name].(map[string]any)
				subtree[name] = mergeMaps(existing, childMap)
			} else {
				nested = append(nested, nestedResult{path: fullPath, content: childMap})
			}
			continue
		}

		if !isYAMLName(name) {
			continue
		}

		content, err := packFile(fullPath, anchors)
		if err != nil {
			return nil, err
		}

		switch {
		case depth == 0:
			// Files directly under the pack root are merged at the top level.
			subtree = mergeMaps(subtree, content)
		case isSpecialName(name):
			// @*.yml files are merged at the current directory level rather than
			// nested under a key. The parent-dir key is consulted to pull in any
			// content already accumulated there (matching the original filetree behaviour).
			existing, _ := subtree[dirBasename].(map[string]any)
			subtree = mergeMaps(subtree, existing, content)
		default:
			key := nameWithoutExt(name)
			existing, _ := subtree[key].(map[string]any)
			subtree[key] = mergeMaps(existing, content)
			origins[key] = fullPath
		}
	}

	for _, n := range nested {
		for key := range n.content {
			if from, taken := origins[key]; taken {
				return nil, fmt.Errorf(
					"%q and %q both define %q; two files that pack into the same section cannot share a name",
					from, filepath.Join(n.path, key+".yml"), key)
			}
			origins[key] = filepath.Join(n.path, key+".yml")
		}
		subtree = mergeMaps(subtree, n.content)
	}

	return subtree, nil
}

// packFile reads and parses a single YAML file, returning its root map.
//
// anchors supplies the anchors defined elsewhere in the tree. A file that aliases
// one of them fails to parse on its own — anchors are a property of a single YAML
// document — so on that specific failure the parse is retried with those
// definitions prepended. Pass nil to parse the file in isolation.
func packFile(path string, anchors map[string]*yaml.Node) (map[string]any, error) {
	b, err := os.ReadFile(path) //#nosec:G304 // path is a resolved filesystem path under the user-supplied pack root directory
	if err != nil {
		return nil, fmt.Errorf("reading %q: %w", path, err)
	}

	v, err := decodeYAML(b)
	if err != nil {
		v, err = retryWithAnchors(b, anchors, err)
		if err != nil {
			return nil, parseError(path, err)
		}
	}
	if v == nil {
		return make(map[string]any), nil
	}
	m := toStringMap(v)
	if m == nil {
		return nil, fmt.Errorf("%q must have a YAML map at the root, got %T", path, v)
	}
	return m, nil
}

// decodeYAML parses one YAML document into a Go value.
//
// It goes through a yaml.Node rather than straight into `any` so that plain
// YAML 1.1 booleans can be retagged before the value is materialised — see
// resolveYAML11Bools for why that matters. A file that is empty, or holds only
// comments, yields a nil value and no error.
//
// The separate Decode step is also what surfaces duplicate mapping keys:
// yaml.Unmarshal into a yaml.Node accepts them, and only the decode into a Go
// value reports them.
func decodeYAML(b []byte) (any, error) {
	var node yaml.Node
	if err := yaml.Unmarshal(b, &node); err != nil {
		return nil, err
	}
	if node.Kind == 0 {
		return nil, nil
	}

	resolveYAML11Bools(&node, false)

	var v any
	if err := node.Decode(&v); err != nil {
		return nil, err
	}
	return v, nil
}

// yaml11Bools maps the plain scalars that YAML 1.1 resolves as booleans, but
// YAML 1.2 — and therefore gopkg.in/yaml.v3 — resolves as strings.
//
// The single-character forms y/Y/n/N are deliberately absent. YAML 1.1 lists
// them, but SnakeYAML (which backs the CircleCI config compiler) does not
// resolve them as booleans, and "n" is a plausible string value in a real
// config. Matching the compiler matters more here than matching the spec.
var yaml11Bools = map[string]string{
	"yes": "true", "Yes": "true", "YES": "true",
	"on": "true", "On": "true", "ON": "true",
	"no": "false", "No": "false", "NO": "false",
	"off": "false", "Off": "false", "OFF": "false",
}

// resolveYAML11Bools retags unquoted yes/no/on/off scalars as booleans.
//
// The CircleCI config compiler reads YAML 1.1, where those six words are
// booleans. gopkg.in/yaml.v3 reads YAML 1.2, where they are strings — so
// packing decoded `default: on` to the string "on" and, because that string
// would be ambiguous on the way out, re-emitted it quoted. A boolean parameter
// then failed validation against its own declared type:
//
//	Parameter error: default value of parameter 'killswitch' is 'on' (type string): expected type boolean
//
// Retagging makes the packed output say what the compiler would have read from
// the source, which is the whole job of pack. `on` becomes `true` rather than
// an unquoted `on`: both are booleans in YAML 1.1 and 1.2, and `true` cannot be
// misread by either.
//
// Two things are left alone:
//
//   - Quoted scalars. A source that says "on" or 'on' asked for the string, and
//     yaml.v3 records that in Style, so the intent survives.
//   - Mapping keys. isKey tracks them through the walk. A key retagged to a
//     boolean would no longer decode into map[string]any, and CircleCI config
//     has no boolean keys.
func resolveYAML11Bools(n *yaml.Node, isKey bool) {
	if n == nil {
		return
	}
	if n.Kind == yaml.ScalarNode {
		if !isKey && n.Tag == "!!str" && n.Style == 0 {
			if b, ok := yaml11Bools[n.Value]; ok {
				n.Tag = "!!bool"
				n.Value = b
			}
		}
		return
	}
	// Mappings alternate key, value, key, value through Content.
	if n.Kind == yaml.MappingNode {
		for i, child := range n.Content {
			resolveYAML11Bools(child, i%2 == 0)
		}
		return
	}
	for _, child := range n.Content {
		resolveYAML11Bools(child, false)
	}
}

// anchorsKey is the throwaway top-level key the anchor definitions are hung
// from when a file is re-parsed. It is deleted before the file's content is
// merged. The name is not valid anywhere in a CircleCI config or orb, so it
// cannot shadow something real.
const anchorsKey = "__circleci_pack_anchors__"

// collectAnchors records every anchor defined by every YAML file under root.
//
// A decomposed orb naturally wants to define shared values once — conventionally
// in an anchors/@anchors.yml — and alias them from the files that need them. YAML
// will not do that on its own: an anchor is scoped to the document that defines
// it, so each file parsed alone fails with "unknown anchor".
//
// Files that fail to parse are skipped rather than reported. A file with an
// unresolved alias is exactly the case this exists to fix, and any genuine syntax
// error in it surfaces from the main pack pass with its own message.
//
// filepath.WalkDir visits lexically, so when two files define the same anchor
// name the later path wins, deterministically.
func collectAnchors(root string) map[string]*yaml.Node {
	anchors := make(map[string]*yaml.Node)

	// Reads go through an os.Root so they cannot follow a symlink out of the
	// pack directory between the walk seeing an entry and this opening it.
	dirRoot, err := os.OpenRoot(root)
	if err != nil {
		return anchors
	}
	// Close errors are immaterial here: this whole function is best-effort, and
	// every real problem with a file is reported by the main pack pass.
	defer func() { _ = dirRoot.Close() }()

	_ = filepath.WalkDir(root, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return nil //nolint:nilerr // unreadable entries are reported by the main pass
		}
		if strings.HasPrefix(d.Name(), ".") && path != root {
			if d.IsDir() {
				return fs.SkipDir
			}
			return nil
		}
		if d.IsDir() || !isYAMLName(d.Name()) {
			return nil
		}

		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return nil
		}
		b, readErr := dirRoot.ReadFile(rel)
		if readErr != nil {
			return nil
		}
		var node yaml.Node
		if yaml.Unmarshal(b, &node) != nil {
			return nil
		}
		collectNodeAnchors(&node, anchors)
		return nil
	})

	return anchors
}

// collectNodeAnchors walks a parsed document recording anchor definitions.
//
// An anchor whose own subtree contains an alias is skipped: re-serialising it in
// isolation would emit that alias with nothing to resolve it against, and one
// such anchor would break the definitions block for every file. Chaining an
// anchor to another anchor therefore only works within a single file.
func collectNodeAnchors(n *yaml.Node, into map[string]*yaml.Node) {
	if n == nil {
		return
	}
	if n.Anchor != "" && !containsAlias(n) {
		into[n.Anchor] = n
	}
	for _, child := range n.Content {
		collectNodeAnchors(child, into)
	}
}

func containsAlias(n *yaml.Node) bool {
	if n.Kind == yaml.AliasNode {
		return true
	}
	for _, child := range n.Content {
		if containsAlias(child) {
			return true
		}
	}
	return false
}

// retryWithAnchors re-parses src with anchors defined ahead of it, for a file
// whose only problem is an alias to an anchor defined in a sibling file.
//
// firstErr is the failure from parsing src alone. Anything other than an unknown
// anchor is returned untouched — this is not a general-purpose second chance.
//
// Which error to report when the retry also fails needs care, because the retry
// parses a synthesised document rather than the user's file:
//
//   - A *yaml.TypeError means the document parsed and only the decode into a Go
//     value objected — so the anchors did resolve, and the remaining problem
//     (a duplicate key, say) is real. Report it, with its line numbers shifted
//     back onto the user's file. Reporting firstErr here would claim the anchor
//     was unknown when it was not.
//   - Anything else is a parse failure that src alone did not have, so it is an
//     artifact of prepending the definitions — a file whose root is a sequence,
//     or one that opens its own document with ---. Report firstErr, which is at
//     least a true statement about the real file.
//
// The retry parses through decodeYAML rather than yaml.Unmarshal so that a file
// which needed a sibling's anchor is treated identically to every other file.
func retryWithAnchors(src []byte, anchors map[string]*yaml.Node, firstErr error) (any, error) {
	if len(anchors) == 0 || !isUnknownAnchorErr(firstErr) {
		return nil, firstErr
	}

	prefix, err := anchorDefinitions(anchors)
	if err != nil {
		return nil, firstErr
	}

	// decodeYAML, not a bare Unmarshal: a file that needed a sibling's anchor
	// must still get YAML 1.1 boolean retagging and duplicate-key detection.
	v, err := decodeYAML(append(prefix, src...))
	if err != nil {
		var typeErr *yaml.TypeError
		if errors.As(err, &typeErr) {
			return nil, shiftLines(typeErr, bytes.Count(prefix, []byte("\n")))
		}
		return nil, firstErr
	}
	// The definitions block did its job during parsing; the aliases in the file
	// are resolved values now, so drop it before the content is merged.
	if m, ok := v.(map[string]any); ok {
		delete(m, anchorsKey)
	}
	return v, nil
}

// lineRefRe matches every line reference in a yaml.v3 decode message. A single
// message can carry more than one, as duplicate-key reports do:
// `line 3: mapping key "dupe" already defined at line 2`.
var lineRefRe = regexp.MustCompile(`line (\d+)`)

// shiftLines moves every line number in a decode error back by offset, undoing
// the lines that anchorDefinitions prepended, so the reported positions point at
// the file the user actually wrote.
func shiftLines(typeErr *yaml.TypeError, offset int) error {
	if offset == 0 {
		return typeErr
	}
	shifted := make([]string, 0, len(typeErr.Errors))
	for _, e := range typeErr.Errors {
		shifted = append(shifted, lineRefRe.ReplaceAllStringFunc(e, func(match string) string {
			n, convErr := strconv.Atoi(lineRefRe.FindStringSubmatch(match)[1])
			if convErr != nil || n-offset < 1 {
				return match
			}
			return fmt.Sprintf("line %d", n-offset)
		}))
	}
	return &yaml.TypeError{Errors: shifted}
}

// anchorDefinitions renders the collected anchors as a single-line mapping entry
// that can be prepended to a file, e.g.
//
//	__circleci_pack_anchors__: [&my-anchor my-value, &other {a: 1}]
//
// Flow style keeps it to one line and self-contained, so prepending it cannot
// disturb the indentation of what follows.
func anchorDefinitions(anchors map[string]*yaml.Node) ([]byte, error) {
	names := make([]string, 0, len(anchors))
	for name := range anchors {
		names = append(names, name)
	}
	sort.Strings(names)

	seq := &yaml.Node{Kind: yaml.SequenceNode, Style: yaml.FlowStyle}
	for _, name := range names {
		def := flowCopy(anchors[name])
		seq.Content = append(seq.Content, def)
	}

	doc := &yaml.Node{Kind: yaml.MappingNode, Content: []*yaml.Node{
		{Kind: yaml.ScalarNode, Tag: "!!str", Value: anchorsKey},
		seq,
	}}

	out, err := yaml.Marshal(doc)
	if err != nil {
		return nil, err
	}
	if !strings.HasSuffix(string(out), "\n") {
		out = append(out, '\n')
	}
	return out, nil
}

// flowCopy deep-copies a node with every collection forced to flow style, so it
// serialises on one line. Copying matters because the source nodes are shared
// across every file that needs them.
func flowCopy(n *yaml.Node) *yaml.Node {
	if n == nil {
		return nil
	}
	cp := *n
	cp.HeadComment, cp.LineComment, cp.FootComment = "", "", ""
	if cp.Kind == yaml.MappingNode || cp.Kind == yaml.SequenceNode {
		cp.Style = yaml.FlowStyle
	}
	cp.Content = nil
	for _, child := range n.Content {
		cp.Content = append(cp.Content, flowCopy(child))
	}
	return &cp
}

// isUnknownAnchorErr reports whether err is yaml.v3's undefined-alias failure.
// yaml.v3 gives it no distinct type, so the message is all there is to match on.
func isUnknownAnchorErr(err error) bool {
	return err != nil && strings.Contains(err.Error(), "unknown anchor")
}

// mergeMaps shallow-merges any number of maps into a new map[string]any.
// nil inputs are silently skipped.
func mergeMaps(maps ...any) map[string]any {
	result := make(map[string]any)
	for _, m := range maps {
		if m == nil {
			continue
		}
		for k, v := range toStringMap(m) {
			result[k] = v
		}
	}
	return result
}

// toStringMap converts map[string]any or map[any]any (yaml.v2 legacy) to map[string]any.
func toStringMap(v any) map[string]any {
	switch m := v.(type) {
	case map[string]any:
		return m
	case map[any]any:
		out := make(map[string]any, len(m))
		for k, val := range m {
			if ks, ok := k.(string); ok {
				out[ks] = val
			}
		}
		return out
	}
	return nil
}

// yamlLineRe matches the "line N: " prefix that gopkg.in/yaml.v3 puts on the
// front of its messages. It appears on both top-level parse errors
// ("yaml: line 4: could not find expected ':'") and on each entry of a
// *yaml.TypeError ("line 6: mapping key \"auth\" already defined at line 3"),
// so one expression handles both after the "yaml: " prefix is trimmed.
var yamlLineRe = regexp.MustCompile(`^line (\d+): `)

// parseError rewrites a gopkg.in/yaml.v3 parse or decode failure so the source
// location leads the message, in the `file:line:` form that editors and
// terminals turn into a clickable link:
//
//	/path/to/src/executors/executorA.yml:6: mapping key "auth" already defined at line 3
//
// rather than yaml.v3's own shape, which buries the filename in prose and puts
// the line on a continuation line:
//
//	parsing "/path/to/src/executors/executorA.yml": yaml: unmarshal errors:
//	  line 6: mapping key "auth" already defined at line 3
//
// A *yaml.TypeError carries one entry per problem found; each gets its own
// located line so a file with several errors reports all of them. Messages with
// no line number degrade to "file: message" — still a location, just a coarser
// one. Columns are not available: yaml.v3 reports lines only.
func parseError(path string, err error) error {
	var typeErr *yaml.TypeError
	if errors.As(err, &typeErr) && len(typeErr.Errors) > 0 {
		located := make([]string, 0, len(typeErr.Errors))
		for _, e := range typeErr.Errors {
			located = append(located, locate(path, e))
		}
		return errors.New(strings.Join(located, "\n"))
	}
	return errors.New(locate(path, strings.TrimPrefix(err.Error(), "yaml: ")))
}

// locate prefixes msg with path, moving any leading "line N: " into the prefix
// so the result reads "path:N: msg".
func locate(path, msg string) string {
	if m := yamlLineRe.FindStringSubmatch(msg); m != nil {
		return fmt.Sprintf("%s:%s: %s", path, m[1], msg[len(m[0]):])
	}
	return fmt.Sprintf("%s: %s", path, msg)
}

var (
	yamlRe    = regexp.MustCompile(`.+\.(yml|yaml)$`)
	specialRe = regexp.MustCompile(`^@.+\.(yml|yaml)$`)
)

func isYAMLName(name string) bool    { return yamlRe.MatchString(name) }
func isSpecialName(name string) bool { return specialRe.MatchString(name) }

func nameWithoutExt(name string) string {
	return strings.TrimSuffix(name, filepath.Ext(name))
}
