// Copyright (c) 2026 Circle Internet Services, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//
// SPDX-License-Identifier: MIT

// Package pack merges a directory tree of YAML files into a single YAML document.
//
// The merge rules are consistent across all CircleCI YAML packing (config and orbs):
//
//   - Files at the pack root are merged at the top level of the output.
//   - Subdirectory names become top-level YAML keys; files inside become entries
//     under that key, keyed by filename without extension.
//   - Files whose names begin with "@" are merged at the current directory level
//     rather than nested under a key (used for base files like @orb.yml).
//   - Dotfiles and non-YAML files are skipped.
//   - Packing a single file round-trips it through the YAML parser (normalising
//     formatting) and returns the result.
//   - Output is indented with four spaces, matching the 0.1.x CLI byte for byte.
package pack

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"
)

// indent is the number of spaces per YAML nesting level in packed output.
//
// Packed configs and orbs are commonly generated by a hook and committed, so the
// exact whitespace is part of the contract: changing it rewrites every line of
// every committed packed file. Four is what the 0.1.x CLI emitted — it marshalled
// with gopkg.in/yaml.v3's default indent — so packing with either CLI produces
// the same bytes and neither churns the other's output.
const indent = 4

// Pack reads all YAML files under rootPath and merges them into a single YAML
// document. If rootPath is a single file it is parsed and re-serialised.
func Pack(rootPath string) (string, error) {
	absRoot, err := filepath.Abs(rootPath)
	if err != nil {
		return "", fmt.Errorf("resolving path: %w", err)
	}

	info, err := os.Stat(absRoot)
	if err != nil {
		if os.IsNotExist(err) {
			return "", fmt.Errorf("accessing %q: no such file or directory", rootPath)
		}
		return "", fmt.Errorf("accessing %q: %w", rootPath, err)
	}

	var result map[string]any
	if info.IsDir() {
		result, err = packDir(absRoot, absRoot)
	} else {
		result, err = packFile(absRoot)
	}
	if err != nil {
		return "", err
	}

	var buf strings.Builder
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(indent)
	err = enc.Encode(result)
	if err != nil {
		return "", fmt.Errorf("marshaling result: %w", err)
	}
	return buf.String(), nil
}

// packDir recursively merges all YAML files under dirPath.
// absRoot identifies which level is the "root" for top-level merge behaviour.
func packDir(dirPath, absRoot string) (map[string]any, error) {
	entries, err := os.ReadDir(dirPath)
	if err != nil {
		return nil, fmt.Errorf("reading directory %q: %w", dirPath, err)
	}

	subtree := make(map[string]any)
	isRoot := dirPath == absRoot
	dirBasename := nameWithoutExt(filepath.Base(dirPath))

	for _, entry := range entries {
		name := entry.Name()
		fullPath := filepath.Join(dirPath, name)

		if strings.HasPrefix(name, ".") {
			continue
		}

		if entry.IsDir() {
			childMap, err := packDir(fullPath, absRoot)
			if err != nil {
				return nil, err
			}
			existing, _ := subtree[name].(map[string]any)
			subtree[name] = mergeMaps(existing, childMap)
			continue
		}

		if !isYAMLName(name) {
			continue
		}

		content, err := packFile(fullPath)
		if err != nil {
			return nil, err
		}

		switch {
		case isRoot:
			// Files directly under the pack root are merged at the top level.
			subtree = mergeMaps(subtree, content)
		case isSpecialName(name):
			// @*.yml files are merged at the current directory level rather than
			// nested under a key. The parent-dir key is consulted to pull in any
			// content already accumulated there (matching the original filetree behaviour).
			existing, _ := subtree[dirBasename].(map[string]any)
			subtree = mergeMaps(subtree, existing, content)
		default:
			key := nameWithoutExt(name)
			existing, _ := subtree[key].(map[string]any)
			subtree[key] = mergeMaps(existing, content)
		}
	}
	return subtree, nil
}

// packFile reads and parses a single YAML file, returning its root map.
func packFile(path string) (map[string]any, error) {
	b, err := os.ReadFile(path) //#nosec:G304 // path is a resolved filesystem path under the user-supplied pack root directory
	if err != nil {
		return nil, fmt.Errorf("reading %q: %w", path, err)
	}
	var v any
	if err := yaml.Unmarshal(b, &v); err != nil {
		return nil, parseError(path, err)
	}
	if v == nil {
		return make(map[string]any), nil
	}
	m := toStringMap(v)
	if m == nil {
		return nil, fmt.Errorf("%q must have a YAML map at the root, got %T", path, v)
	}
	return m, nil
}

// mergeMaps shallow-merges any number of maps into a new map[string]any.
// nil inputs are silently skipped.
func mergeMaps(maps ...any) map[string]any {
	result := make(map[string]any)
	for _, m := range maps {
		if m == nil {
			continue
		}
		for k, v := range toStringMap(m) {
			result[k] = v
		}
	}
	return result
}

// toStringMap converts map[string]any or map[any]any (yaml.v2 legacy) to map[string]any.
func toStringMap(v any) map[string]any {
	switch m := v.(type) {
	case map[string]any:
		return m
	case map[any]any:
		out := make(map[string]any, len(m))
		for k, val := range m {
			if ks, ok := k.(string); ok {
				out[ks] = val
			}
		}
		return out
	}
	return nil
}

// yamlLineRe matches the "line N: " prefix that gopkg.in/yaml.v3 puts on the
// front of its messages. It appears on both top-level parse errors
// ("yaml: line 4: could not find expected ':'") and on each entry of a
// *yaml.TypeError ("line 6: mapping key \"auth\" already defined at line 3"),
// so one expression handles both after the "yaml: " prefix is trimmed.
var yamlLineRe = regexp.MustCompile(`^line (\d+): `)

// parseError rewrites a gopkg.in/yaml.v3 parse or decode failure so the source
// location leads the message, in the `file:line:` form that editors and
// terminals turn into a clickable link:
//
//	/path/to/src/executors/executorA.yml:6: mapping key "auth" already defined at line 3
//
// rather than yaml.v3's own shape, which buries the filename in prose and puts
// the line on a continuation line:
//
//	parsing "/path/to/src/executors/executorA.yml": yaml: unmarshal errors:
//	  line 6: mapping key "auth" already defined at line 3
//
// A *yaml.TypeError carries one entry per problem found; each gets its own
// located line so a file with several errors reports all of them. Messages with
// no line number degrade to "file: message" — still a location, just a coarser
// one. Columns are not available: yaml.v3 reports lines only.
func parseError(path string, err error) error {
	var typeErr *yaml.TypeError
	if errors.As(err, &typeErr) && len(typeErr.Errors) > 0 {
		located := make([]string, 0, len(typeErr.Errors))
		for _, e := range typeErr.Errors {
			located = append(located, locate(path, e))
		}
		return errors.New(strings.Join(located, "\n"))
	}
	return errors.New(locate(path, strings.TrimPrefix(err.Error(), "yaml: ")))
}

// locate prefixes msg with path, moving any leading "line N: " into the prefix
// so the result reads "path:N: msg".
func locate(path, msg string) string {
	if m := yamlLineRe.FindStringSubmatch(msg); m != nil {
		return fmt.Sprintf("%s:%s: %s", path, m[1], msg[len(m[0]):])
	}
	return fmt.Sprintf("%s: %s", path, msg)
}

var (
	yamlRe    = regexp.MustCompile(`.+\.(yml|yaml)$`)
	specialRe = regexp.MustCompile(`^@.+\.(yml|yaml)$`)
)

func isYAMLName(name string) bool    { return yamlRe.MatchString(name) }
func isSpecialName(name string) bool { return specialRe.MatchString(name) }

func nameWithoutExt(name string) string {
	return strings.TrimSuffix(name, filepath.Ext(name))
}
