name: circleci
version: "%CLI_VERSION_PLACEHOLDER%"
summary: "Run local CI builds and validate configuration."
description: |
  The CircleCI Local CLI allows you to run builds on your local machine as if they were running within CircleCI. This allows quick interation over small changes and easier debugging of issues. The Local CLI can also validate your CircleCI configuration file.
grade: stable
confinement: strict
base: core24
parts:
  circleci:
    plugin: nil
    override-build: |
      cp dist/circleci-cli_linux_amd64_v1/circleci $CRAFT_PART_INSTALL/bin/circleci
      chmod +x $CRAFT_PART_INSTALL/bin/circleci
    stage-packages: [docker.io]
apps:
  circleci:
    plugs:
      - docker
      - home
      - network
    command: circleci
